
services:
  # Define the service for the database
    
  authentication:
    build:
      context: ./Services/Authentication/
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
  
    
  ai:
    build:
      context: ./Services/AI/
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
   
    
  patient:
    build:
      context: ./Services/Patient/
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
   
    
    

  doctor:
    build:
      context: ./Services/Doctor/
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

    
    

  admin:
    build:
      context: ./Services/Admin/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    
# # Define a shared network for services
networks:
  app-network:
    driver: bridge

