
services:
  # Define the service for the database
  database:
    build:
      context: ./Services/Database/
      dockerfile: Dockerfile
    ports:
      - "4999:4999"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://subhash:12@cluster0.h1e1a.mongodb.net/MediScribe?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network
    
  authentication:
    build:
      context: ./Services/Authentication/
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - database
    command: sh -c "./wait-for-it.sh database:4999 -- npm start"
    
  ai:
    build:
      context: ./Services/AI/
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    depends_on:
      - database
    
  patient:
    build:
      context: ./Services/Patient/
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - database
    
    

  doctor:
    build:
      context: ./Services/Doctor/
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - database
    
    

  admin:
    build:
      context: ./Services/Admin/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    
# # Define a shared network for services
networks:
  app-network:
    driver: bridge

